name: github-actions
on:
  push:
  pull_request:
    branches:
      - "main"
      - "MVE1-READ_MAP"

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive' # Include submodules when checking out the repository

      - name: Initialize libft submodule
        run: git submodule update --init libft

      - name: Update libft submodule
        run: git submodule update --remote libft

      - name: 42 NORM
        uses: alexandregv/norminette-action@v3.3.51
        with:
          flags: '.'

      - name: Fsanitize Test
        if: github.event_name == 'pull_request'
        run: make debug=true test

      - name: Classic Test
        if: github.event_name == 'pull_request'
        run: make re test

      # - name: Install Valgrind
      #   run: sudo apt-get install valgrind
      # - name: Valgrind Test
      #   if: github.event_name == 'pull_request'
      #   run: make valgrind=true test
